spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-config-client
---
server:
  port: 8201
spring:
  profiles: test #测试环境
  application:
    name: microservicecloud-config-client